kind: Service
apiVersion: v1
metadata:
  name: usermanagmentservice
spec:
  selector:
    app: usermanagmentservice
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagmentservice-deployment
  labels:
    app: usermanagmentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagmentservice
  template:
    metadata:
      labels:
        app: usermanagmentservice
    spec:
      containers:
      - name: usermanagmentservice
        image: citybikeshare/usermanagmentservice:latest
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        env:
          - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
            value: http://consul:8500  
          - name: KUMULUZEE_CONFIG_CONSUL_AGENT
            value: http://consul:8500
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-usermanagment:5432/postgres
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: postgres
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: admin
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        