kumuluzee:
  name: cityBikeShare
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/cityBikeShareDS
    connection-url: jdbc:postgresql://localhost:5432/cityBikeShare
    username: postgres
    password: admin
    max-pool-size: 20